### ISSUE TITLE
input file as CLI argument

### ISSUE THREAD

**Issue by za3k** [derhuerst/url-decode-encode-cli#4]
If you run `url-decode -h` etc, the program hangs, waiting for stdin. Instead, you should display a command-line usage guide and exit if there are any unexpected arguments (any arguments).

Also, I would suggest allowing `url-decode FILE1 [FILE2]` as an alternative to `url-decode <FILE1 >FILE2`

**Comment by derhuerst** [comment]
> If you run `url-decode -h` etc, the program hangs, waiting for stdin. Instead, you should display a command-line usage guide and exit if there are any unexpected arguments (any arguments).

Fixed as of df8df4a, published as `url-decode-encode-cli@1.0.1`!

> Also, I would suggest allowing `url-decode FILE1 [FILE2]` as an alternative to `url-decode <FILE1 >FILE2`

Is there a certain workflow that is enabled by this form? Because otherwise, if there's no real benefit, I'd like to keep this tool as simple as possible.

**Comment by za3k** [comment]
Nothing gets enabled AFAIK, it's just a convenience. `url-decode FILE1` in particular is something a lot of people will expect to output to stdout, it's a common *nix thing. As long as you're printing a usage message that seems fine too.

**Comment by derhuerst** [comment]
Okay, a PR is welcome then!

**Comment by za3k** [comment]
Added a PR, but i'd point out https://github.com/derhuerst/url-decode-encode-cli/commit/df8df4a31aed9a169febeef1c398819d3d85a5af didn't fix one fundamental problem: if you encounter unknown CLI arguments, the program should error out, not silently ignore them.
